In [1]:
!git clone https://github.com/hyeshik/colab-biolab.git
!cd colab-biolab && bash tools/setup.sh
exec(open('colab-biolab/tools/activate_conda.py').read())

fatal: destination path 'colab-biolab' already exists and is not an empty directory.
./
./root/
./root/.bashrc.biolab
tar: ./root/.bashrc.biolab: Cannot open: Permission denied
./root/.bin.priority/
tar: ./root/.bin.priority: Cannot mkdir: Permission denied
./root/.bin.priority/pip
tar: ./root/.bin.priority/pip: Cannot open: Permission denied
./root/.bin.priority/pip2
tar: ./root/.bin.priority/pip2: Cannot open: Permission denied
./root/.bin.priority/pip3
tar: ./root/.bin.priority/pip3: Cannot open: Permission denied
./root/.condarc
tar: ./root/.condarc: Cannot open: Permission denied
./root/.profile
tar: ./root/.profile: Cannot open: Permission denied
./root/.tmux.conf
tar: ./root/.tmux.conf: Cannot open: Permission denied
./root/.vimrc
tar: ./root/.vimrc: Cannot open: Permission denied
tar: ./root: Cannot utime: Operation not permitted
tar: ./root: Cannot change mode to rwxr-xr-x: Operation not permitted
tar: .: Cannot utime: Operation not permitted
tar: Exiting with failure status due to previous errors
mkdir: cannot create directory ‘/root’: Permission denied
ERROR: Could not create directory: '/root/conda'
cat: /rna/youngjoon/.bashrc.biolab: No such file or directory

/bin/bash: line 2: /root/conda/bin/conda: Permission denied

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.

ValueError: not enough values to unpack (expected 2, got 1)

In [2]:
!conda install -y bedtools bioawk samtools

Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 23.3.1
  latest version: 24.5.0

Please update conda by running

    $ conda update -n base -c conda-forge conda

Or to minimize the number of packages updated during conda update use

     conda install conda=24.5.0



# All requested packages already installed.

In [26]:
!grep -i mirlet7g ../binfo1-datapack1/gencode.gtf
!grep -i mirlet7f-1 ../binfo1-datapack1/gencode.gtf
!grep -i mirlet7d ../binfo1-datapack1/gencode.gtf

chr9	ENSEMBL	gene	106056039	106056126	.	+	.	gene_id "ENSMUSG00000065440.3"; gene_type "miRNA"; gene_name "Mirlet7g"; level 3; mgi_id "MGI:2676800";
chr9	ENSEMBL	transcript	106056039	106056126	.	+	.	gene_id "ENSMUSG00000065440.3"; transcript_id "ENSMUST00000083506.3"; gene_type "miRNA"; gene_name "Mirlet7g"; transcript_type "miRNA"; transcript_name "Mirlet7g-201"; level 3; transcript_support_level "NA"; mgi_id "MGI:2676800"; tag "basic";
chr9	ENSEMBL	exon	106056039	106056126	.	+	.	gene_id "ENSMUSG00000065440.3"; transcript_id "ENSMUST00000083506.3"; gene_type "miRNA"; gene_name "Mirlet7g"; transcript_type "miRNA"; transcript_name "Mirlet7g-201"; exon_number 1; exon_id "ENSMUSE00000522665.2"; level 3; transcript_support_level "NA"; mgi_id "MGI:2676800"; tag "basic";
chr13	ENSEMBL	gene	48691305	48691393	.	-	.	gene_id "ENSMUSG00000105621.3"; gene_type "miRNA"; gene_name "Mirlet7f-1"; level 3; mgi_id "MGI:2676798";
chr13	ENSEMBL	transcript	48691305	48691393	.	-	.	gene_id "ENSMUSG00000105621.3"; transcript_id "ENSMUST00000198652.3"; gene_type "miRNA"; gene_name "Mirlet7f-1"; transcript_type "miRNA"; transcript_name "Mirlet7f-1-201"; level 3; transcript_support_level "NA"; mgi_id "MGI:2676798"; tag "basic";
chr13	ENSEMBL	exon	48691305	48691393	.	-	.	gene_id "ENSMUSG00000105621.3"; transcript_id "ENSMUST00000198652.3"; gene_type "miRNA"; gene_name "Mirlet7f-1"; transcript_type "miRNA"; transcript_name "Mirlet7f-1-201"; exon_number 1; exon_id "ENSMUSE00001348852.2"; level 3; transcript_support_level "NA"; mgi_id "MGI:2676798"; tag "basic";
chr13	ENSEMBL	gene	48689488	48689590	.	-	.	gene_id "ENSMUSG00000065453.3"; gene_type "miRNA"; gene_name "Mirlet7d"; level 3; mgi_id "MGI:2676796";
chr13	ENSEMBL	transcript	48689488	48689590	.	-	.	gene_id "ENSMUSG00000065453.3"; transcript_id "ENSMUST00000083519.3"; gene_type "miRNA"; gene_name "Mirlet7d"; transcript_type "miRNA"; transcript_name "Mirlet7d-201"; level 3; transcript_support_level "NA"; mgi_id "MGI:2676796"; tag "basic";
chr13	ENSEMBL	exon	48689488	48689590	.	-	.	gene_id "ENSMUSG00000065453.3"; transcript_id "ENSMUST00000083519.3"; gene_type "miRNA"; gene_name "Mirlet7d"; transcript_type "miRNA"; transcript_name "Mirlet7d-201"; exon_number 1; exon_id "ENSMUSE00000522678.2"; level 3; transcript_support_level "NA"; mgi_id "MGI:2676796"; tag "basic";

In [27]:
!samtools view -b -o CLIP-let7g.bam ../binfo1-datapack1/CLIP-35L33G.bam chr9:106056039-106056126
!samtools view CLIP-let7g.bam | wc -l
!samtools view -b -o CLIP-let7f_1.bam ../binfo1-datapack1/CLIP-35L33G.bam chr13:48691305-48691393
!samtools view CLIP-let7f_1.bam | wc -l
!samtools view -b -o CLIP-let7d.bam ../binfo1-datapack1/CLIP-35L33G.bam chr13:48689488-48689590
!samtools view CLIP-let7d.bam | wc -l

163
158
187

In [28]:
!samtools mpileup CLIP-let7g.bam > CLIP-let7g.pileup
!wc -l CLIP-let7g.pileup
!head CLIP-let7g.pileup

!samtools mpileup CLIP-let7f_1.bam > CLIP-let7f_1.pileup
!wc -l CLIP-let7f_1.pileup
!head CLIP-let7f_1.pileup

!samtools mpileup CLIP-let7d.bam > CLIP-let7d.pileup
!wc -l CLIP-let7d.pileup
!head CLIP-let7d.pileup

[mpileup] 1 samples in 1 input files
68548 CLIP-let7g.pileup
chr9	106007092	N	9	^Ga^Ia^Ha^Ia^Ga^Ga^Ha^Ia^Ia	<IFIGGHII
chr9	106007093	N	9	ggggggggg	AFGIEGDII
chr9	106007094	N	9	ccccccccc	EHHIGAFEH
chr9	106007095	N	9	aaaaaaaaa	?HDIFA>II
chr9	106007096	N	9	aaaaaaaaa	EHHIG@CHH
chr9	106007097	N	9	ttttttttt	=HGEGDFII
chr9	106007098	N	9	aaaaaaaaa	?HHIGDEII
chr9	106007099	N	9	g-2nng-2nng-2nng-2nng-2nng-2nng-2nng-2nng-2nn	?IEHGEDII
chr9	106007100	N	9	*********	8IBIBC@EI
chr9	106007101	N	9	*********	8IBIBC@EI
[mpileup] 1 samples in 1 input files
97 CLIP-let7f_1.pileup
chr13	48691290	N	1	^Gg	A
chr13	48691291	N	26	c^Hc^Ic^Dc^Hc^Gc^Ic^Gc^Ic^Gc^Ic^Ic^Hc^Hc^Hc^Ec^Ic^Ic^Ic^Hc^Hc^Hc^Ic^Ic^Ic^Hc	DDI4G>I@H;GGGFH7IHIHHHFIIG
chr13	48691292	N	25	aaaaaaaaaaaaaaaaaaaaaaaaa	DGIG>IBI?IIGHH7HIEHFFGHIG
chr13	48691293	N	38	gggggggggggggggggggggggggg^Ig^Hg^Ig^Ig^Ig^Ig^Hg^Ig^Ig^Dg^Ig^Ig	DGI4>AIGIBIIGGE/IIIDGHIIIHEGIHIIBIIBII
chr13	48691294	N	49	cccccccccccccccccccccccccccccccccccccc^Ec^Hc^Ic^Hc^Hc^Gc^Ic^Ic^Gc^Ic^Hc	?>I1E5IDG<I>EHH7IIIFHHEIHGCEDIHIEHG?II3BIDD7IHGGH
chr13	48691295	N	58	aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa^Ha^Ia^Ha^Ha^Ha^Ia^Ia^Ia^Ha	BDI?HBIGHGIHGHG7IIIGBGIIIGBEFIIIBIH=II=EIGA6IHGIHDIHGGIII0
chr13	48691296	N	81	aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa^Ia^Ia^Da^Ia^Ha^Ia^Ha^Ga^Ha^Ha^Ga^Ia^Ha^Ha^Ia^Ha^Ha^Ia^Ha^Ia^Ga^Ia^Ga	<GI7H?IGIEIIGHG;FIIGGHIIIGIBGDIHGII@II9FHDA9IIGGHGIEGGIIIBEIBIHIG;DG?IBHICGIHI6I;
chr13	48691297	N	80	gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg	8EI.HBIGIGIGGHG1IIIGGGIIIEIBGGIIDII=II=FIGD5IIGDHDIHGGIGH@DIDGDIB1GGDIHGD=EHHGH5
chr13	48691298	N	80	tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt	GI4H7IGIGIIGHG7IHIGDHIGIGIBGGHIDIH@II?EIGG=IIGIHDGHG8IFH7DH@HHIG1GH9HDHI<GIDB.H/
chr13	48691299	N	80	cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc	<<I7H=I@I;IHGGG7HIIGGHGGHGFEBIEIDII=II:HIC><IIGIHGHGEGIII;HGBIHGD;GF<IGHICEIDII4
[mpileup] 1 samples in 1 input files
87 CLIP-let7d.pileup
chr13	48689488	N	24	^Ga^Ia^Ha^Ia^Ha^Ia^Ia^Ia^Ga^Ia^Ia^Ia^Ia^Ia^Ha^Ia^Ga^Ga^Ga^Ia^Ea^Da^Ha^Ga	BIHGGIHIEIIIGIHIGEGH5BDD
chr13	48689489	N	53	aaaaaaaaaaaaaaaaaaaaaaaaa^Ia^Ha^Ia^Ga^Ga^Ha^Ia^Ia^Ga^Ga^Ia^Ia^Ha^Ia^Ia^Ha^Ha^Da^Ia^Ha^Ia^Ia^Ia^Ia^Ia^Ha^Ga^Ga	GIHIGIIIEIIIIIHIG>EB4@5HDIHIBEGIID?IIGII@H>IGHIIIGHDC
chr13	48689490	N	69	ttttttttttttttttttttttttttttttttttttttttttttttttttttt^Gt^Gt^Ht^Gt^It^It^Ht^It^Gt^Gt^Ht^It^It^It^Ht^It	GIHIGHIFFIIIIIFHGEDG;2>FDIHIDGBIIDBIIDIIAH>IBGIIIGHBG=BG=IIGIDGHFIIHI
chr13	48689491	N	105	aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa^Ia^Ia^Ha^Ga^Ia^Ga^Ia^Ga^Ha^Ha^Ha^Ga^Ia^Ha^Ha^Ia^@a^Ia^Ia^Ia^Ga^Ha^Ha^Ga^Ha^Ga^Ia^Ha^Ga^Ia^Ga^Ha^Ga^Ia^Ia^Ga	EIGHEHHIEIIIIIHIGCBH:?>HGGHI>GBIIGBIIGIHBB;IHIIIIGHDC3=G:IGGIDEHIFIGHII=GIDHEGHHEIGGI7III9=HGBAIGBIGFG>I2
chr13	48689492	N	105	aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa	GIGIEIEI7IIIGIGIG;?F:D@G7GHIAGAIIG3IIGIHDB2IHIIIIDDGC1<GCIIHIGCHIIIEIIIGCIBIEGHH?HHFI9IIIA=GGB?IEGIFEGGIA
chr13	48689493	N	105	ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg	BIEIGHGI7IHHGIGHG=?F58>E5EHIAGAHIDAHIGII:EDHHIHIIGG>>5EDAIIFFGDHIIHGIII8EIDIBBHHBIGHI7HII?=GGBEIG>HFEGGIA
chr13	48689494	N	105	ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg	FIFEGIFE3HFIGIGHG=?D1?@D5EHIAEADIBFIIGHIBD<IHDGIIGBD>03GEEIHF@DHIIIDIIHEAIDIC>HHBHFDI9FIIE=GGBAIGEFEEGIIA
chr13	48689495	N	104	cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc	GID>GHEG.HIHGH>IG2;B;?>E0BCI8G?FGA?HH@HIB?DHBIIIHGBG90BAEIEF8CEDIHGIIHGAI?I3BGH;HHHE7IIIA=GG:?IFEBF2GBI;
chr13	48689496	N	102	cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc	FI8EEGEI.GEB<ID>G38B19>BFFI<D<FGAEFIGDFB@@CH>EHH8B7>BDCEEEBBCHBGEEFHIG?I;IG@HH2EEGI9IIIA>;<@IE<E:CDIG<
chr13	48689497	N	104	cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc	DIHFBIFG.HIIFIGIB3;B993E:IGHAGDIDC3IIHDIBDHBIIIII>;58?A>IIEHBAHBHIGHIEFBI0BG<HHEEGDG.III?7H?>3IE<H8EDGG?

In [29]:
!awk '$2 >= 106056039 && $2 <= 106056126 { print $0; }' CLIP-let7g.pileup > CLIP-let7g-gene.pileup
!tail CLIP-let7g-gene.pileup

!awk '$2 >= 48691305 && $2 <= 48691393 { print $0; }' CLIP-let7f_1.pileup > CLIP-let7f_1-gene.pileup
!tail CLIP-let7f_1-gene.pileup

!awk '$2 >= 48689488 && $2 <= 48689590 { print $0; }' CLIP-let7d.pileup > CLIP-let7d-gene.pileup
!tail CLIP-let7d-gene.pileup

chr9	106056117	N	138	<<<<<<<<<CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC	BHEIG?DIIHGHII:;HGIIDGGGIIBGEB?>H<GGIIIIDIIGFHIHH9IGG=GGHIDH?DGIBIIHHGGIEIGI8GIDHDG.GGHEDIIDIDGDHIDGIFGHG;DCDDHEE@I?CGG:IHGIBGIHIIDG@DHIGG
chr9	106056118	N	139	<<<<<<<<<CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC	BHEIG?DIIHGHII3AHIIIDGGGIIB3EHFBH>GIIIIIIIIIHIIHHAIIGBDGHIDH?GIIGIIHHDIIHIGIGGI=BGG9GIHHHIIGI=IAIIGGIEHGIEBG@DHDE;IBDGG4IGGIGGIIIIGGGDGIH1G
chr9	106056119	N	138	<<<<<<<<<TTTTTTTTTTTTTTTTTTTTTTTTTT$TTTT$TTTTTTTTTTTTTTT$TTTT$TTTTTTT$TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT	BHEIG?DIIGEFII:/GIIEDDHDIIF>BH3<HBEGIHIGFIIIBIIBE:HHGD>EGGDH7BIIGGIHHDHIHDEIGEIDHGG;GIHGHHIGD:IGHD:GGEHH?3G87HD</I=DGG=IHHIHBIFII@<HDHHH1G
chr9	106056120	N	133	<<<<<<<<<TTTTTTTTTTTTTTTTTTTTTTTTTTTT$TTTT$TTT$TTTTTTTTTT$TTTTTTTT$TTTTTTTTTTTT$T$TTTTTT$TTTT$TT$TTTTTTTTTTTTTTTTTTT$TTTTTTTTTTTTTTTTTTTTTTTTTTT	BHEIG?DIIHFBII74BIIIGDIIIIA8DHECHBIIIIIIIIHIIHB?IDGGGFDH?GIIIIHH@GHHGEDDGIEHBEDIHHGIIGI:HBII8DIIHHIBDD;<HDD3HB?@G?HHIIHIIIIIB@HDHDH8G
chr9	106056121	N	118	<<<<<<<<<GGGGGGGGGGGGGGGGGGGG$G$G$G$G$G$G$G$GGGGGG$GG$GGGG$GG$GGGG$G$GGG$GGG$GGG$GGGG$GGGGG$GGGGGGGGG$GGGGGG$GG$GGG$GGG$GGGG$G$GG$GGGGGG$GGGG$G$G$G$G$G$	BHEIG?DIIB<EDI/7BHHFB<FGHI3?GG>HAIHIFEF@H<<2>D3EE;HBAIIIBH4IHG@DI>G482GGFHID:I9II@BH@>HE8@;<HGI:GGBIDEIBIGIIIE?G@EIH7G
chr9	106056122	N	88	<<<<<<<<<C$C$C$C$C$C$C$C$C$C$C$C$C$CCCCCC$C$C$C$C$C$C$CCC$C$C$C$CC$C$CC$CC$C$C$C$C$C$C$C$C$C$C$C$C$C$CC$C$C$C$C$C$CC$CC$C$CCC$C$C$C$C$CCCCC$CCC$C	BHEIG?DIIEEGIIC;GIHEGBIIIIB1=FII?FEIGGGHDBIG=HHIIEBHD>EIHIG=I:HGBIIEF?E;DB3HB<GIHIHHEADF
chr9	106056123	N	31	<<<<<<<<<CCCCCCCCCCCCCCCCCCCCCC	BHEIG?DIIIIII>GIGGIGGD>BIHHHIEH
chr9	106056124	N	31	<<<<<<<<<AAAAAAAAAAAAAAAAAAAAAA	BHEIG?DIIIIHIGGIGGGIG:9DDBIEGFH
chr9	106056125	N	31	<<<<<<<<<GGGGGGGGGGGGGGGGGGGGGG	BHEIG?DIIIIIIGGE@GFIGD;GIGIIFHD
chr9	106056126	N	30	<<<<<<<<<GGGGGGGGGGGGGGGGGGGGG	BHEIG?DIIIIGHGHIGHI>G;GGGIGIHG
chr13	48691377	N	24	tttttttttttttttttttttttt	BIIGIGEDCGFIFGI@GHIDDIGI
chr13	48691378	N	24	aaaaaaaaaaaaaaaaaaaaaaaa	?HIFIGGGAFEFABI>GII;EIGI
chr13	48691379	N	24	cccccccccccccccccccccccc	EIIGIGGDEGGIEGI;GIIDDIGI
chr13	48691380	N	24	tttttttttttttttttttttttt	EIIGIBGGEGFIFGI@GIIBDIGI
chr13	48691381	N	24	aaaaaaaaaaaaaaaaaaaaaaaa	BEHFIGEG@FCEAGH4GII;AIDH
chr13	48691382	N	24	cccccccccccccccccccccccc	?IEGIHGG?GEGEBI=GIIDEIGG
chr13	48691383	N	24	cccccccccccccccccccccccc	EIGGIGGGAGFGFGI=GIIDGIGG
chr13	48691384	N	24	tttttttttttttttttttttttt	<IGGIHGG>GEGBGI8GII@GIGG
chr13	48691385	N	24	cccccccccccccccccccccccc	BIGGIBDD?GEGBEI=GIIBGIGG
chr13	48691386	N	24	a$a$a$a$a$a$a$a$a$a$a$a$a$a$a$a$a$a$a$a$a$a$a$a$	EIGGIFDECGFGFGI2BIIDGIGG
chr13	48689565	N	6	cccccc	>IGIIH
chr13	48689566	N	6	tttttt	:IGFIH
chr13	48689567	N	6	aaaaaa	8IFIFI
chr13	48689568	N	6	cccccc	?IGIII
chr13	48689569	N	6	tttttt	;IGIII
chr13	48689570	N	5	aaaaa	EDECD
chr13	48689571	N	6	cccccc	:GGIGG
chr13	48689572	N	6	cccccc	:GGIGG
chr13	48689573	N	6	tttttt	5GGIGG
chr13	48689574	N	6	c$c$c$c$c$c$	;GGIGG

In [35]:
import pandas as pd 

pileup_Mirlet7g = pd.read_csv('CLIP-let7g-gene.pileup', sep = '\t', names = ['chrom', 'pos', '_ref', 'count', 'basereads', 'quals'])
pileup_Mirlet7g.tail()

pileup_Mirlet7f_1 = pd.read_csv('CLIP-let7f_1-gene.pileup', sep = '\t', names = ['chrom', 'pos', '_ref', 'count', 'basereads', 'quals'])
pileup_Mirlet7f_1.tail()

pileup_Mirlet7d = pd.read_csv('CLIP-let7d-gene.pileup', sep = '\t', names = ['chrom', 'pos', '_ref', 'count', 'basereads', 'quals'])
pileup_Mirlet7d.tail()

    chrom       pos _ref  count     basereads   quals
82  chr13  48689570    N      5         aaaaa   EDECD
83  chr13  48689571    N      6        cccccc  :GGIGG
84  chr13  48689572    N      6        cccccc  :GGIGG
85  chr13  48689573    N      6        tttttt  5GGIGG
86  chr13  48689574    N      6  c$c$c$c$c$c$  ;GGIGG

In [36]:
import re
toremove = re.compile('[<>$*#^]')
pileup_Mirlet7g['matches'] = pileup_Mirlet7g['basereads'].apply(lambda x: toremove.sub('',x))
pileup_Mirlet7f_1['matches'] = pileup_Mirlet7f_1['basereads'].apply(lambda x: toremove.sub('',x))
pileup_Mirlet7d['matches'] = pileup_Mirlet7d['basereads'].apply(lambda x: toremove.sub('',x))

In [42]:
pileup_Mirlet7g[['chrom', 'pos', 'matches']]
pileup_Mirlet7f_1[['chrom', 'pos', 'matches']]
pileup_Mirlet7d[['chrom', 'pos', 'matches']]

    chrom       pos                                            matches
0   chr13  48689488   GaIaHaIaHaIaIaIaGaIaIaIaIaIaHaIaGaGaGaIaEaDaHaGa
1   chr13  48689489  aaaaaaaaaaaaaaaaaaaaaaaaaIaHaIaGaGaHaIaIaGaGaI...
2   chr13  48689490  tttttttttttttttttttttttttttttttttttttttttttttt...
3   chr13  48689491  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...
4   chr13  48689492  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...
..    ...       ...                                                ...
82  chr13  48689570                                              aaaaa
83  chr13  48689571                                             cccccc
84  chr13  48689572                                             cccccc
85  chr13  48689573                                             tttttt
86  chr13  48689574                                             cccccc

[87 rows x 3 columns]

In [38]:
pileup_Mirlet7g[pileup_Mirlet7g['pos'] == 106056094].iloc[0]['matches']

'GGGGGGAAAAAAAAGGGGGAAAAAAGCCGCAGGATGAGGTGATAAGGGAGGGGTGAAGGGCGGTGAAGGGGAAAAGAGAAAGAAAAATAAAGGGGGAGTGGGAGGAAGAAGAGAATA'

In [50]:
import pandas as pd
import numpy as np
from collections import Counter

bed_Mirlet7g= pileup_Mirlet7g[['chrom', 'pos']].copy()
bed_Mirlet7g.columns = ['chr', 'start_position']
bed_Mirlet7g['end_position'] = bed_Mirlet7g['start_position']+1



def calculate_entropy(row):
    bases = ['A', 'T', 'C', 'G']
    entropy = 0
    count_dict = Counter(row)
    for base in bases:
        count = count_dict.get(base, 0)
        total = sum(count_dict.values())
        p = count / total if total > 0 else 0
        if p > 0:
            entropy -= p * np.log2(p)
    return entropy

bed_Mirlet7g['entropy'] = pileup_Mirlet7g['matches'].str.upper().apply(calculate_entropy).copy()
bed_Mirlet7g.to_csv('Mirlet7g.bedgraph', sep='\t', header=False, index=False)
bed_Mirlet7g

     chr  start_position  end_position  entropy
0   chr9       106056039     106056040      0.0
1   chr9       106056040     106056041      0.0
2   chr9       106056041     106056042      0.0
3   chr9       106056042     106056043      0.0
4   chr9       106056043     106056044      0.0
..   ...             ...           ...      ...
83  chr9       106056122     106056123      0.0
84  chr9       106056123     106056124      0.0
85  chr9       106056124     106056125      0.0
86  chr9       106056125     106056126      0.0
87  chr9       106056126     106056127      0.0

[88 rows x 4 columns]

In [53]:
import pandas as pd
import numpy as np
from collections import Counter

bed_Mirlet7f_1= pileup_Mirlet7f_1[['chrom', 'pos']].copy()
bed_Mirlet7f_1.columns = ['chr', 'start_position']
bed_Mirlet7f_1['end_position'] = bed_Mirlet7f_1['start_position']+1



def calculate_entropy(row):
    bases = ['A', 'T', 'C', 'G']
    entropy = 0
    count_dict = Counter(row)
    for base in bases:
        count = count_dict.get(base, 0)
        total = sum(count_dict.values())
        p = count / total if total > 0 else 0
        if p > 0:
            entropy -= p * np.log2(p)
    return entropy

bed_Mirlet7f_1['entropy'] = pileup_Mirlet7f_1['matches'].str.upper().apply(calculate_entropy).copy()
bed_Mirlet7f_1.to_csv('Mirlet7f-1.bedgraph', sep='\t', header=False, index=False)
bed_Mirlet7f_1

      chr  start_position  end_position  entropy
0   chr13        48691305      48691306      0.0
1   chr13        48691306      48691307      0.0
2   chr13        48691307      48691308      0.0
3   chr13        48691308      48691309      0.0
4   chr13        48691309      48691310      0.0
..    ...             ...           ...      ...
77  chr13        48691382      48691383      0.0
78  chr13        48691383      48691384      0.0
79  chr13        48691384      48691385      0.0
80  chr13        48691385      48691386      0.0
81  chr13        48691386      48691387      0.0

[82 rows x 4 columns]

In [52]:
import pandas as pd
import numpy as np
from collections import Counter

bed_Mirlet7d= pileup_Mirlet7d[['chrom', 'pos']].copy()
bed_Mirlet7d.columns = ['chr', 'start_position']
bed_Mirlet7d['end_position'] = bed_Mirlet7d['start_position']+1



def calculate_entropy(row):
    bases = ['A', 'T', 'C', 'G']
    entropy = 0
    count_dict = Counter(row)
    for base in bases:
        count = count_dict.get(base, 0)
        total = sum(count_dict.values())
        p = count / total if total > 0 else 0
        if p > 0:
            entropy -= p * np.log2(p)
    return entropy

bed_Mirlet7d['entropy'] = pileup_Mirlet7d['matches'].str.upper().apply(calculate_entropy).copy()
bed_Mirlet7d.to_csv('Mirlet7d.bedgraph', sep='\t', header=False, index=False)
bed_Mirlet7d

      chr  start_position  end_position   entropy
0   chr13        48689488      48689489  0.875000
1   chr13        48689489      48689490  0.678538
2   chr13        48689490      48689491  0.484672
3   chr13        48689491      48689492  0.603819
4   chr13        48689492      48689493  0.000000
..    ...             ...           ...       ...
82  chr13        48689570      48689571  0.000000
83  chr13        48689571      48689572  0.000000
84  chr13        48689572      48689573  0.000000
85  chr13        48689573      48689574  0.000000
86  chr13        48689574      48689575  0.000000

[87 rows x 4 columns]